### ISSUE TITLE
gitlab: Actions - fix YAML file  showscores/.github/workflows/shellcheck.yml

### ISSUE THREAD

**Issue by roseswe** [roseswe/showscores#4]
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2

**Comment by thomas-merz** [comment]
Have a look at [this issue](https://github.com/actions-js/push/issues/11) - it should be fixed there by a new release. Still waiting for it… Thinking about a fork of this repo in my personal space if actions won't work anymore due to "still no release" and use this instead… 🤔

**Comment by thomasmerz** [comment]
Sorry, this is the wrong issue!!! Please have a look at https://github.com/actions/checkout/pull/689 . You only have to change [this line](https://github.com/roseswe/showscores/blob/master/.github/workflows/shellcheck.yml#L27):
```
      - uses: actions/checkout@latest
```

**Comment by thomas-merz** [comment]
@roseswe Sorry, this has been the wrong issue!!!   
Please have a look at https://github.com/actions/checkout/pull/689 . You only have to change [this line](https://github.com/roseswe/showscores/blob/master/.github/workflows/shellcheck.yml#L27) to one of these:
```
      - uses: actions/checkout@latest
      - uses: actions/checkout@v3
      - uses: actions/checkout@master
```

**Comment by thomas-merz** [comment]
See https://github.com/roseswe/showscores/commit/74d598d5c0077c4a111778418ccb5c7ca1cfa8e5 and resulting [GH Action](https://github.com/roseswe/showscores/actions/runs/3687224868 )👍
